name: CI

on:
  push:
    branches:
      - master
      - feature/lambda-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, test, pack
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
        yarn run build
        yarn run test
        yarn run pack
      env:
        CI: true
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@v0.0.1
      with:
        function-name: pokedex-alexa-skill
        zip-file: pokedexalexaskill.zip

      
