name: CI

on:
  push:
    branches:
      - master
      - feature/lambda-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: yarn install, build, test, pack
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
        yarn run build
        yarn run test
        yarn run pack
      env:
        CI: true
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: zip-file
        path: pokedexalexaskill.zip
    
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: zip-file
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@v0.0.1
      with:
        --function-name: pokedex-alexa-skill
        --zip-file: pokedexalexaskill.zip
        --dry-run: true