name: Continuous Deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: yarn install, build, test, pack
      run: |
        npm install -g yarn
        yarn install --frozen-lockfile
        yarn run build
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
        yarn run test
        yarn run pack
      env:
        CI: true
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: deployable
        path: pokedexalexaskill.zip
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: deployable
    - name: AWS Lambda Deploy
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
        aws configure set output json
        aws lambda update-function-code --function-name pokedex-alexa-skill-dev --zip-file fileb://deployable/pokedexalexaskill.zip

  deploy-prod:
    # Only deploy to production on push to 'master' branch
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: [build, deploy-dev]

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: deployable
    - name: AWS Lambda Deploy
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
        aws configure set output json
        aws lambda update-function-code --function-name pokedex-alexa-skill --zip-file fileb://deployable/pokedexalexaskill.zip